apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: geozarr-convert-
spec:
  entrypoint: run-convert
  templates:
  - name: run-convert
    inputs:
      parameters:
        - name: stac_url
          value: "https://objectstore.eodc.eu:2222/e05ab01a9d56408d82ac32d69a5aae2a:202505-s02msil2a/18/products/cpm_v256/S2B_MSIL2A_20250518T112119_N0511_R037_T29RLL_20250518T140519.zarr"
        - name: output_zarr
          value: "./S2B_MSIL2A_20250518_T29RLL_geozarr.zarr"
        - name: groups
          value: "measurements/reflectance/r20m"
        - name: dask_perf_html
          value: "out/debug/dask-report-threads.html"
    script:
      image: eopf-geozarr:dev
      command: ["sh"]
      source: |
        set -eu
        mkdir -p "$(dirname "{{inputs.parameters.dask_perf_html}}")"
        eopf-geozarr convert \
          --dask-cluster \
          --dask-perf-html "{{inputs.parameters.dask_perf_html}}" \
          "{{inputs.parameters.stac_url}}" \
          "{{inputs.parameters.output_zarr}}" \
          --verbose \
          --groups "{{inputs.parameters.groups}}"
        tar -czf geozarr.tar.gz -C "$(dirname "{{inputs.parameters.output_zarr}}")" "$(basename "{{inputs.parameters.output_zarr}}")"
      resources:
        requests:
          cpu: "2"
          memory: "4Gi"
        limits:
          cpu: "4"
          memory: "8Gi"
    outputs:
      artifacts:
        - name: dask-report
          path: "{{inputs.parameters.dask_perf_html}}"
        - name: geozarr-tar
          path: geozarr.tar.gz
