name: Documentation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    paths:
      - "docs/**"

jobs:
  build-docs:
    permissions:
      contents: write
      pages: write   
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5

    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version: '3.11'

    - name: Install uv
      uses: astral-sh/setup-uv@v7
      with:
        version: "0.8.4"
        python-version: "3.13"
        enable-cache: false

    - name: Install dependencies
      run: uv sync --group docs

    - name: Build docs
      if: github.event_name == 'pull_request'
      run: uv run -- mkdocs build

    - name: Deploy docs
      if: github.event_name == 'push'
      run: uv run -- mkdocs gh-deploy --force
